sudo: required
language: minimal
branches:
  only:
    - master
services:
  - docker
dist: bionic
env:
  global:
    # Since Travis is on AWS, it's public IP isn't the address AWS security groups see. 
    # So we need to drop that restriction for Travis - i.e. allow access from everywhere
    - MAKEFLAGS="-j 1 ACCESS_CIDR=0.0.0.0/0"
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - sudo apt-get -y install make
  - sudo ssh-keygen -t rsa -b 4096 -C "Testing" -f ~/.ssh/id_rsa -N ""
install:
  - sudo make install-dependencies
script:
  - sudo make deploy
  - sudo make infra-deploy-wait
  - sudo make server-push
  - sudo make install
  - sudo make test
after_script:
  - sudo make destroy